name: Build iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build iOS
        run: flutter build ios --release --no-codesign
      
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/Runner.app

      - name: Display build output
        run: ls -a build/ios/Runner.app
